apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    spec:
      containers:
      - name: main
        image: arm7tdmi/simple-flask-webapp:latest
