apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml
commonLabels:
  env: prod
images:
- name: simple-flask-webapp
  newName: arm7tdmi/simple-flask-webapp
  newTag: "v0.1"